# .github/workflows/daily-deploy-hook.yml
name: Daily Redeploy via Hook
on:
  schedule:
    - cron: "0 0 * * *" # UTC时间每天0点
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy
        run: |
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
